from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one match, found {count}")
    p.write_text(text.replace(old, new, 1))


reader = "mreader/ReaderView.swift"
integration = "mreader/TranslationComicIntegration.swift"
tests = "mreaderTests/TranslationComicIntegrationRegressionTests.swift"

replace_once(
    reader,
    '''                    TranslationSurfaceRenderer(\n                        layoutSize: item.rect.size,\n                        surfaceStyle: item.surfaceStyle,\n                        displayMode: item.displayMode\n                    )''',
    '''                    TranslationSurfaceRenderer(\n                        layoutSize: item.rect.size,\n                        surfaceStyle: item.surfaceStyle,\n                        displayMode: item.displayMode,\n                        layoutStatus: item.layoutStatus\n                    )'''
)

replace_once(
    reader,
    '''            occupiedRects.append(rect.insetBy(dx: -4, dy: -4))\n            items.append(TranslationLayoutItem(\n                blocks: item.blocks,\n                rect: rect,''',
    '''            let presentationRect: CGRect\n            if layoutStatus == .needsExpansion {\n                let compactPreview = TranslationOverflowPresentationPolicy.compactPreviewRect(\n                    sourceRect: mappedSourceRect,\n                    allowedBounds: movementBounds,\n                    orientation: item.textOrientation\n                )\n                presentationRect = OCRBubbleLayoutEngine.nonOverlappingRect(\n                    compactPreview,\n                    anchor: CGPoint(x: mappedSourceRect.midX, y: mappedSourceRect.midY),\n                    occupiedRects: occupiedRects,\n                    bounds: movementBounds,\n                    margin: 0\n                )\n            } else {\n                presentationRect = rect\n            }\n\n            occupiedRects.append(presentationRect.insetBy(dx: -4, dy: -4))\n            items.append(TranslationLayoutItem(\n                blocks: item.blocks,\n                rect: presentationRect,'''
)

replace_once(
    reader,
    '''private struct TranslationSurfaceRenderer: View {\n    let layoutSize: CGSize\n    let surfaceStyle: TranslationSurfaceStyle\n    let displayMode: TranslationDisplayMode\n\n    @ViewBuilder\n    var body: some View {\n        switch displayMode {\n        case .inPlace:\n            RoundedRectangle(cornerRadius: max(surfaceStyle.cornerRadius * 0.55, 3), style: .continuous)\n                .fill(Color.white.opacity(0.94))\n                .frame(width: layoutSize.width, height: layoutSize.height)\n        case .assistOverlay:\n            RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                .fill(.ultraThinMaterial)\n                .overlay {\n                    RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                        .fill(Color.white.opacity(surfaceStyle.backgroundOpacity))\n                }\n                .overlay {\n                    RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                        .strokeBorder(Color.white.opacity(surfaceStyle.borderOpacity), lineWidth: 0.75)\n                        .shadow(color: .black.opacity(0.34), radius: 0.8, y: 0.6)\n                }\n                .frame(width: layoutSize.width, height: layoutSize.height)\n        case .annotation:\n            RoundedRectangle(cornerRadius: 5, style: .continuous)\n                .fill(.thinMaterial)\n                .overlay {\n                    RoundedRectangle(cornerRadius: 5, style: .continuous)\n                        .fill(Color.white.opacity(0.30))\n                }\n                .frame(width: layoutSize.width, height: layoutSize.height)\n        }\n    }\n}\n''',
    '''private struct TranslationSurfaceRenderer: View {\n    let layoutSize: CGSize\n    let surfaceStyle: TranslationSurfaceStyle\n    let displayMode: TranslationDisplayMode\n    let layoutStatus: OCRBubbleLayoutEngine.TranslationLayoutStatus\n\n    @ViewBuilder\n    var body: some View {\n        if layoutStatus == .needsExpansion {\n            // Overflow is a compact, low-obstruction preview. The full text is\n            // opened only after the user taps this specific region.\n            RoundedRectangle(cornerRadius: min(max(surfaceStyle.cornerRadius * 0.6, 4), 8), style: .continuous)\n                .fill(.ultraThinMaterial)\n                .overlay {\n                    RoundedRectangle(cornerRadius: min(max(surfaceStyle.cornerRadius * 0.6, 4), 8), style: .continuous)\n                        .fill(Color.white.opacity(0.18))\n                }\n                .overlay {\n                    RoundedRectangle(cornerRadius: min(max(surfaceStyle.cornerRadius * 0.6, 4), 8), style: .continuous)\n                        .strokeBorder(Color.white.opacity(0.28), lineWidth: 0.6)\n                }\n                .frame(width: layoutSize.width, height: layoutSize.height)\n        } else {\n            switch displayMode {\n            case .inPlace:\n                RoundedRectangle(cornerRadius: max(surfaceStyle.cornerRadius * 0.55, 3), style: .continuous)\n                    .fill(Color.white.opacity(0.94))\n                    .frame(width: layoutSize.width, height: layoutSize.height)\n            case .assistOverlay:\n                RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                    .fill(.ultraThinMaterial)\n                    .overlay {\n                        RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                            .fill(Color.white.opacity(surfaceStyle.backgroundOpacity))\n                    }\n                    .overlay {\n                        RoundedRectangle(cornerRadius: surfaceStyle.cornerRadius, style: .continuous)\n                            .strokeBorder(Color.white.opacity(surfaceStyle.borderOpacity), lineWidth: 0.75)\n                            .shadow(color: .black.opacity(0.34), radius: 0.8, y: 0.6)\n                    }\n                    .frame(width: layoutSize.width, height: layoutSize.height)\n            case .annotation:\n                RoundedRectangle(cornerRadius: 5, style: .continuous)\n                    .fill(.thinMaterial)\n                    .overlay {\n                        RoundedRectangle(cornerRadius: 5, style: .continuous)\n                            .fill(Color.white.opacity(0.30))\n                    }\n                    .frame(width: layoutSize.width, height: layoutSize.height)\n            }\n        }\n    }\n}\n'''
)

replace_once(
    reader,
    '''    var body: some View {\n        Group {\n            if layoutStatus == .needsExpansion {\n                Button {\n                    isExpansionPresented = true\n                } label: {\n                    Image(systemName: "text.magnifyingglass")\n                        .font(.system(size: max(min(fontSize, 18), 12), weight: .semibold))\n                        .foregroundStyle(style.coreTextColor.swiftUIColor)\n                        .frame(maxWidth: .infinity, maxHeight: .infinity)\n                        .contentShape(Rectangle())\n                }\n                .buttonStyle(.plain)\n                .accessibilityLabel("ocr.translationNeedsExpansion".localized)\n            } else {\n                CoreTextTranslationView(\n                    text: fullText,\n                    fontSize: fontSize,\n                    color: displayMode == .inPlace ? UIColor.label : style.coreTextColor,\n                    textOrientation: textOrientation,\n                    lineSpacing: 2\n                )\n            }\n        }\n        .padding(contentPadding)\n        .frame(width: layoutSize.width, height: layoutSize.height)''',
    '''    var body: some View {\n        Group {\n            if layoutStatus == .needsExpansion {\n                Button {\n                    isExpansionPresented = true\n                } label: {\n                    ZStack(alignment: .bottomTrailing) {\n                        // Keep a real translation preview visible at the readable\n                        // floor. The preview may clip, but it must never degrade\n                        // into an icon-only card.\n                        CoreTextTranslationView(\n                            text: fullText,\n                            fontSize: fontSize,\n                            color: displayMode == .inPlace ? UIColor.label : style.coreTextColor,\n                            textOrientation: textOrientation,\n                            lineSpacing: 2\n                        )\n                        .allowsHitTesting(false)\n\n                        Image(systemName: "arrow.up.left.and.arrow.down.right")\n                            .font(.system(size: 8, weight: .bold))\n                            .foregroundStyle(style.coreTextColor.swiftUIColor)\n                            .padding(3)\n                            .background(.ultraThinMaterial, in: Circle())\n                            .padding(2)\n                    }\n                    .contentShape(Rectangle())\n                }\n                .buttonStyle(.plain)\n                .accessibilityLabel("ocr.translationNeedsExpansion".localized)\n                .accessibilityValue(fullText)\n            } else {\n                CoreTextTranslationView(\n                    text: fullText,\n                    fontSize: fontSize,\n                    color: displayMode == .inPlace ? UIColor.label : style.coreTextColor,\n                    textOrientation: textOrientation,\n                    lineSpacing: 2\n                )\n            }\n        }\n        .padding(layoutStatus == .needsExpansion ? min(contentPadding, 3) : contentPadding)\n        .frame(width: layoutSize.width, height: layoutSize.height)\n        .clipped()'''
)

insert_after = '''nonisolated enum TranslationDisplayPolicy {\n    static func mode(\n        contentRole: TranslationContentRole,\n        hasReliableDetectedBubble: Bool,\n        prefersInPlace: Bool\n    ) -> TranslationDisplayMode {\n        switch contentRole {\n        case .dialogue where hasReliableDetectedBubble && prefersInPlace:\n            return .inPlace\n        case .soundEffect:\n            return .annotation\n        case .dialogue, .narration, .other:\n            return .assistOverlay\n        }\n    }\n}\n'''
addition = '''\n/// Rendering fallback for translations that cannot fit at the configured\n/// readable floor. Overflow remains visible as a small preview anchored to the\n/// source region; only the selected region opens the full scrollable text.\nnonisolated enum TranslationOverflowPresentationPolicy {\n    static func compactPreviewRect(\n        sourceRect: CGRect,\n        allowedBounds: CGRect,\n        orientation: TextOrientation\n    ) -> CGRect {\n        let bounds = allowedBounds.standardized\n        guard !bounds.isNull, bounds.width > 0, bounds.height > 0 else {\n            return sourceRect.standardized\n        }\n\n        let source = sourceRect.standardized\n        let minimum = orientation == .vertical\n            ? CGSize(width: 36, height: 64)\n            : CGSize(width: 64, height: 32)\n        let maximum = orientation == .vertical\n            ? CGSize(width: 56, height: 120)\n            : CGSize(width: 120, height: 56)\n\n        let width = min(max(source.width, min(minimum.width, bounds.width)), min(maximum.width, bounds.width))\n        let height = min(max(source.height, min(minimum.height, bounds.height)), min(maximum.height, bounds.height))\n        let desiredX = source.midX - width / 2\n        let desiredY = source.midY - height / 2\n        let x = min(max(desiredX, bounds.minX), bounds.maxX - width)\n        let y = min(max(desiredY, bounds.minY), bounds.maxY - height)\n        return CGRect(x: x, y: y, width: width, height: height)\n    }\n}\n'''
replace_once(integration, insert_after, insert_after + addition)

marker = '''    func testLayoutSafeRegionIsConstrainedByPhysicalBubbleWithoutBecomingBubbleEvidence() {'''
new_tests = '''    func testOverflowPreviewIsCompactAnchoredAndBoundedForHorizontalText() {\n        let bounds = CGRect(x: 10, y: 20, width: 360, height: 520)\n        let source = CGRect(x: 150, y: 180, width: 210, height: 90)\n        let rect = TranslationOverflowPresentationPolicy.compactPreviewRect(\n            sourceRect: source,\n            allowedBounds: bounds,\n            orientation: .horizontal\n        )\n\n        XCTAssertTrue(bounds.insetBy(dx: -0.5, dy: -0.5).contains(rect))\n        XCTAssertLessThanOrEqual(rect.width, 120)\n        XCTAssertLessThanOrEqual(rect.height, 56)\n        XCTAssertGreaterThanOrEqual(rect.width, 64)\n        XCTAssertGreaterThanOrEqual(rect.height, 32)\n        XCTAssertEqual(rect.midX, source.midX, accuracy: 0.5)\n    }\n\n    func testOverflowPreviewForVerticalTextNeverExpandsIntoLargeAssistCard() {\n        let bounds = CGRect(x: 0, y: 0, width: 280, height: 600)\n        let source = CGRect(x: 228, y: 120, width: 24, height: 250)\n        let rect = TranslationOverflowPresentationPolicy.compactPreviewRect(\n            sourceRect: source,\n            allowedBounds: bounds,\n            orientation: .vertical\n        )\n\n        XCTAssertTrue(bounds.insetBy(dx: -0.5, dy: -0.5).contains(rect))\n        XCTAssertLessThanOrEqual(rect.width, 56)\n        XCTAssertLessThanOrEqual(rect.height, 120)\n        XCTAssertGreaterThanOrEqual(rect.width, 36)\n        XCTAssertGreaterThanOrEqual(rect.height, 64)\n        XCTAssertLessThan(rect.width * rect.height, source.width * source.height * 1.2)\n    }\n\n'''
replace_once(tests, marker, new_tests + marker)

print("translation expansion patch applied")
